- hosts: 192.168.1.215
  become: yes
  become_method: sudo
  #remote_user: use
  tasks:
  #- name: Check Java version
  #  command: java -version
     
  # - name: Download Weblogic binary
  #   unarchive:
  #    src: https://download.jboss.org/wildfly/19.1.0.Final/wildfly-19.1.0.Final.tar.gz
  #    dest: /home/user1/ansible_playbook
  #    remote_src: yes
  #    extra_opts: [--strip-components=1]
  # - name: Change host name of configuration files
  #   replace:
  #     path: /home/user1/Oracle/Middleware/Oracle_Home/user_projects/domains/base_domain/init-info/startscript.xml
  #     regexp: 'ubuntv2064bit'
  #     replace: 'centosv18test.jmrinfotechblr.com'
  #     backup: yes
  #   replace:
  #     path: /home/user1/Oracle/Middleware/Oracle_Home/user_projects/domains/base_domain/init-info/user_projects/domains/base_domain/init-info/tokenValue.properties
  #     regexp: 'ubuntv2064bit'
  #     replace: 'centosv18test.jmrinfotechblr.com'
  #     backup: yes
  #   replace:
  #     path: /home/user1/Oracle/Middleware/Oracle_Home/user_projects/domains/base_domain/bin/startManagedWebLogic.sh
  #     regexp: 'ubuntv2064bit'
  #     replace: 'centosv18test.jmrinfotechblr.com'
  #     backup: yes
  #   replace:
  #     path: /home/user1/Oracle/Middleware/Oracle_Home/user_projects/domains/base_domain/bin/stopManagedWebLogic.sh
  #     regexp: 'ubuntv2064bit'
  #     replace: 'centosv18test.jmrinfotechblr.com'
  #     backup: yes
  #   replace:
  #     path: /home/user1/Oracle/Middleware/Oracle_Home/user_projects/domains/base_domain/bin/stopWebLogic.sh
  #     regexp: 'ubuntv2064bit'
  #     replace: 'centosv18test.jmrinfotechblr.com'
  #     backup: yes

  - name: Run Weblogic
    shell:  nohup sh /home/user1/Oracle/Middleware/Oracle_Home/user_projects/domains/base_domain/bin/startWebLogic.sh &
  